[package]
name = "rust-openfmb-ops-protobuf"
version = "0.1.0"
authors = ["Dwayne Bradley <dwayne.bradley@gmail.com>"]
edition = "2018"

[dependencies]
prost = "0.5.0"
prost-types = "0.5.0"
bytes = "0.4.12"
num = "0.2.0"
